_wandb:
    value:
        cli_version: 0.18.1
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.18.1
            "8":
                - 5
            "12": 0.18.1
            "13": linux-x86_64
activation_function:
    value: gelu
big_skip:
    value: false
embed_dim:
    value: 32
encoder_kernel_shape:
    value:
        - 4
        - 4
filter_basis_type:
    value: morlet
grid:
    value: legendre-gauss
img_size:
    value:
        - 181
        - 360
kernel_shape:
    value:
        - 4
        - 4
normalization_layer:
    value: none
num_layers:
    value: 4
operator_type:
    value: driscoll-healy
pos_embed:
    value: false
scale_factor:
    value: 2
upsample_sht:
    value: true
use_mlp:
    value: true
