## Start with Debian slim-bullseye - https://medium.com/@arif.rahman.rhm/choosing-the-right-python-docker-image-slim-buster-vs-alpine-vs-slim-bullseye-5586bac8b4c9

ARG VERSION_DATE=latest
ARG FROM_IMAGE=nasanccs/qefm-core-debian

# Import NVIDIA Modulus container as the BASE Image (Modulus base image)
FROM ${FROM_IMAGE}:${VERSION_DATE}
LABEL maintainer="glenn.s.tamkin@nasa.gov" 

ENV PYTHONPATH="$PYTHONPATH:/qefm-core/qefm/models/src/FMGenCast/graphcast:/qefm-core/qefm/models/src/FMGenCast"

# GraphCast dependencies
#RUN pip install git+git://github.com/deepmind/jraph.git
RUN pip install jax
#RUN pip install cartopy
#RUN pip install Cartopy
RUN pip install chex
RUN pip install dm-haiku

RUN pip install trimesh
RUN pip install Rtree
RUN pip install pyglet
#RUN pip install --index-url=https://blpapi.bloomberg.com/repository/releases/python/simple blpapi
#RUN pip install embreex==2.17.7.post5
RUN pip install manifold3d
RUN pip install lxml
RUN pip install drawsvg
#RUN pip install vhacdx
RUN pip install xxhash

# Aurora dependencies
RUN pip install cdsapi

RUN pip install torch

HEALTHCHECK NONE
ENTRYPOINT [""]
