## Start with Debian slim-bullseye - https://medium.com/@arif.rahman.rhm/choosing-the-right-python-docker-image-slim-buster-vs-alpine-vs-slim-bullseye-5586bac8b4c9
# Choose Slim Bullseye if:
# You want a newer base image with reasonable size.
# You prefer the familiarity of Debian while benefiting from some size reduction.

#FROM node:18
FROM python:3.10-slim-bullseye
LABEL maintainer="glenn.s.tamkin@nasa.gov" 

RUN pip install --upgrade setuptools pip wheel
RUN pip install nvidia-pyindex
RUN pip install nvidia-cuda-runtime-cu12

#RUN pip install cartopy

# GPU dependencies
RUN pip install --upgrade "jax[cuda12]"

# GenCast dependencies
RUN pip install --upgrade xarray netCDF4 h5netcdf
RUN pip install IPython

# GraphCast dependencies
RUN pip install dm-haiku
RUN pip install dm-tree
RUN pip install matplotlib
RUN pip install chex
RUN pip install jraph
RUN pip install dask
RUN pip install trimesh

RUN pip install Pint
RUN pip install tree_math 
#RUN pip install tensorstore 
#RUN pip install xarray_tensorstore

#RUN pip install --no-cache-dir https://github.com/deepmind/graphcast/archive/master.zip
#RUN pip install -vvv --disable-pip-version-check --no-cache-dir --no-deps https://github.com/deepmind/graphcast/archive/master.zip 

HEALTHCHECK NONE
ENTRYPOINT [""]
