FROM python:3.12-slim-bookworm
COPY --from=ghcr.io/astral-sh/uv:0.7.11 /uv /uvx /bin/

# Where we're installing this thing.
ARG APP_HOME="/opt/facts-total"

# Use custom user/group so container not run with root permissions.
#USER 9876:9876

WORKDIR ${APP_HOME}

# Install git (required for cloning)
RUN apt-get update && \
    apt-get install -y git openssh-client && \
    rm -rf /var/lib/apt/lists/*

# Clone the repository using SSH
# This requires BuildKit and SSH agent forwarding
RUN --mount=type=ssh,id=default \
    mkdir -p ~/.ssh && \
    ssh-keyscan github.com >> ~/.ssh/known_hosts && \
    git clone https://github.com/fact-sealevel/facts-total.git ${APP_HOME} && \
#    git clone git@github.com:fact-sealevel/facts-total.git ${APP_HOME} && \
    rm -rf ~/.ssh

# Install the application dependencies into a local virtual environment, compiling to bytecode.
RUN uv sync --frozen --no-cache --no-dev --compile-bytecode

# Easily run commands from the environment just created.
ENV PATH="${APP_HOME}/.venv/bin:$PATH"

ENTRYPOINT ["facts-total"]
