# Arguments to pass to the image
ARG VERSION_DATE=3.21.3
ARG FROM_IMAGE=alpine

# Import NVIDIA Modulus container as the BASE Image (Modulus base image)
#FROM ${FROM_IMAGE}:${VERSION_DATE}
FROM python:3.10.10-alpine
LABEL maintainer="glenn.s.tamkin@nasa.gov" 

# Install Python
#RUN apk add --no-cache python3 py3-pip

# GenCast dependencies
RUN pip install --no-deps https://github.com/deepmind/graphcast/archive/master.zip
RUN pip install --no-deps xarray netCDF4 h5netcdf
RUN pip install IPython
RUN pip install --upgrade "jax[cuda12]"

# GraphCast dependencies
RUN pip install git+git://github.com/deepmind/jraph.git
RUN pip install jax
RUN pip install Cartopy
RUN pip install chex
RUN pip install dm-haiku

RUN pip install trimesh
RUN pip install Rtree
RUN pip install pyglet
RUN pip install --index-url=https://blpapi.bloomberg.com/repository/releases/python/simple blpapi
RUN pip install embreex==2.17.7.post5
RUN pip install manifold3d
RUN pip install lxml
RUN pip install drawsvg
RUN pip install vhacdx
RUN pip install xxhash

# Aurora dependencies
RUN pip install cdsapi

HEALTHCHECK NONE
ENTRYPOINT [""]
