# Arguments to pass to the image
ARG VERSION_DATE=latest
ARG FROM_IMAGE=nasanccs/qefm-core

# Import NVIDIA Modulus container as the BASE Image (Modulus base image)
FROM ${FROM_IMAGE}:${VERSION_DATE}
LABEL maintainer="glenn.s.tamkin@nasa.gov" 

# GenCast dependencies
RUN pip install tree_math
RUN pip install xarray_tensorstore

WORKDIR /app
RUN git clone --branch main https://github.com/neuralgcm/dinosaur.git

HEALTHCHECK NONE
ENTRYPOINT [""]
CMD ["/bin/bash"]
