## Start with Debian slim-bullseye - https://medium.com/@arif.rahman.rhm/choosing-the-right-python-docker-image-slim-buster-vs-alpine-vs-slim-bullseye-5586bac8b4c9
# Choose Slim Bullseye if:
# You want a newer base image with reasonable size.
# You prefer the familiarity of Debian while benefiting from some size reduction.

FROM python:3.10-slim-bullseye
LABEL maintainer="glenn.s.tamkin@nasa.gov" 

RUN pip install --upgrade setuptools pip wheel
RUN pip install nvidia-pyindex
RUN pip install nvidia-cuda-runtime-cu12

# GraphCast dependencies
RUN pip install --no-cache-dir https://github.com/deepmind/graphcast/archive/master.zip

# GPU dependencies
RUN pip install --upgrade "jax[cuda12]"

# GenCast dependencies
RUN pip install --upgrade xarray netCDF4 h5netcdf
RUN pip install IPython

# AISF dependencies
RUN pip install -q anemoi-inference[huggingface]==0.4.3 anemoi-models==0.2.1
RUN pip install -q earthkit-regrid ecmwf-opendata
RUN pip install nvidia-cuda-nvcc
RUN pip install flash_attn
RUN pip install matplotlib
RUN pip install cartopy

HEALTHCHECK NONE
ENTRYPOINT [""]
