## Start with Debian slim-bullseye - https://medium.com/@arif.rahman.rhm/choosing-the-right-python-docker-image-slim-buster-vs-alpine-vs-slim-bullseye-5586bac8b4c9

ARG VERSION_DATE=latest
ARG FROM_IMAGE=nasanccs/qefm-core-debian-all

# Import NVIDIA Modulus container as the BASE Image (Modulus base image)
FROM ${FROM_IMAGE}:${VERSION_DATE}
LABEL maintainer="glenn.s.tamkin@nasa.gov" 

#RUN apt-get install nvidia-cuda-toolkit

RUN apt-get update && apt-get install -y curl
RUN apt-get install -y sed
RUN apt-get install -y sudo
RUN apt-get install -y gpg
RUN curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg \
  && curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
    sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
    tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
#RUN apt-get update
RUN apt-get install -y nvidia-container-toolkit

# Compile faster..
RUN pip install ninja

# AIFS dependencies
#RUN pip install -q anemoi-inference[huggingface]==0.4.3 anemoi-models==0.2.1
#RUN pip install -q earthkit-regrid==0.3.4 ecmwf-opendata
#RUN pip install -q flash_attn

ENV NVTE_FLASH_ATTN=0
ENV NVTE_FLASH_ATTN_2=0

RUN pip install anemoi-inference[huggingface]==0.4.9 anemoi-models==0.3.1
RUN pip install earthkit-regrid==0.4.0 ecmwf-opendata 
#RUN pip install flash-attn --no-build-isolation

WORKDIR /app

RUN git clone https://github.com/HazyResearch/flash-attention.git

WORKDIR /app/flash-attention
RUN echo "PYTHONPATH = $PYTHONPATH"
ENV PYTHONPATH="$PYTHONPATH:/app/flash-attention"
RUN echo "PYTHONPATH = $PYTHONPATH"

RUN pwd
RUN ls -alt
RUN python setup.py install
#RUN pip install -e .

HEALTHCHECK NONE
ENTRYPOINT [""]
