## Start with Debian slim-bullseye - https://medium.com/@arif.rahman.rhm/choosing-the-right-python-docker-image-slim-buster-vs-alpine-vs-slim-bullseye-5586bac8b4c9
# Choose Slim Bullseye if:
# You want a newer base image with reasonable size.
# You prefer the familiarity of Debian while benefiting from some size reduction.

FROM python:3.10-slim-bullseye
LABEL maintainer="glenn.s.tamkin@nasa.gov" 

# GPU dependencies
RUN pip install --upgrade "jax[cuda12]"

# GraphCast dependencies
RUN pip install --no-cache-dir --no-deps https://github.com/deepmind/graphcast/archive/master.zip

# GenCast dependencies
RUN pip install --upgrade xarray netCDF4 h5netcdf
RUN pip install IPython
RUN pip install absl-py

# Aurora dependencies
RUN pip install cdsapi

HEALTHCHECK NONE
ENTRYPOINT [""]
